name: Build react app

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build react app
        uses: actions/setup-node@v2
        with:
          node-version: 16.15.0
          cache: 'npm'
      - run: npm install
      - run: npm run build
